# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_windowmJqecy.ui'
##
## Created by: Qt User Interface Compiler version 6.8.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QApplication, QCheckBox, QFrame,
    QHeaderView, QLabel, QLineEdit, QListWidget,
    QListWidgetItem, QMainWindow, QPushButton, QRadioButton,
    QSizePolicy, QStatusBar, QTabWidget, QTableWidget,
    QTableWidgetItem, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(797, 505)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setSizeIncrement(QSize(1, 1))
        MainWindow.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setSizeIncrement(QSize(1, 1))
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QRect(0, 0, 800, 500))
        self.tab_main = QWidget()
        self.tab_main.setObjectName(u"tab_main")
        sizePolicy.setHeightForWidth(self.tab_main.sizePolicy().hasHeightForWidth())
        self.tab_main.setSizePolicy(sizePolicy)
        self.tab_main.setSizeIncrement(QSize(1, 1))
        self.list_data = QListWidget(self.tab_main)
        QListWidgetItem(self.list_data)
        self.list_data.setObjectName(u"list_data")
        self.list_data.setGeometry(QRect(0, 0, 800, 41))
        self.label_7 = QLabel(self.tab_main)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(400, 50, 221, 20))
        self.label_6 = QLabel(self.tab_main)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(0, 50, 161, 20))
        self.lineEdit_v2 = QLineEdit(self.tab_main)
        self.lineEdit_v2.setObjectName(u"lineEdit_v2")
        self.lineEdit_v2.setGeometry(QRect(270, 50, 101, 21))
        self.lineEdit_v1 = QLineEdit(self.tab_main)
        self.lineEdit_v1.setObjectName(u"lineEdit_v1")
        self.lineEdit_v1.setGeometry(QRect(170, 50, 101, 21))
        self.list_const = QListWidget(self.tab_main)
        QListWidgetItem(self.list_const)
        self.list_const.setObjectName(u"list_const")
        self.list_const.setGeometry(QRect(0, 80, 800, 41))
        self.checkBox_vol = QCheckBox(self.tab_main)
        self.checkBox_vol.setObjectName(u"checkBox_vol")
        self.checkBox_vol.setGeometry(QRect(330, 130, 111, 21))
        self.checkBox_reuse = QCheckBox(self.tab_main)
        self.checkBox_reuse.setObjectName(u"checkBox_reuse")
        self.checkBox_reuse.setGeometry(QRect(120, 130, 111, 21))
        self.checkBox_clean = QCheckBox(self.tab_main)
        self.checkBox_clean.setObjectName(u"checkBox_clean")
        self.checkBox_clean.setGeometry(QRect(240, 130, 81, 21))
        self.pushButton_start = QPushButton(self.tab_main)
        self.pushButton_start.setObjectName(u"pushButton_start")
        self.pushButton_start.setGeometry(QRect(10, 130, 93, 29))
        self.line = QFrame(self.tab_main)
        self.line.setObjectName(u"line")
        self.line.setEnabled(True)
        self.line.setGeometry(QRect(0, 160, 800, 16))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy1)
        self.line.setMinimumSize(QSize(0, 0))
        font = QFont()
        font.setBold(False)
        self.line.setFont(font)
        self.line.setFrameShadow(QFrame.Shadow.Plain)
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line_2 = QFrame(self.tab_main)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(0, 210, 781, 20))
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.checkBox_lock6 = QCheckBox(self.tab_main)
        self.checkBox_lock6.setObjectName(u"checkBox_lock6")
        self.checkBox_lock6.setGeometry(QRect(370, 420, 21, 24))
        self.lineEdit_b2 = QLineEdit(self.tab_main)
        self.lineEdit_b2.setObjectName(u"lineEdit_b2")
        self.lineEdit_b2.setGeometry(QRect(250, 270, 101, 21))
        self.checkBox_lock8 = QCheckBox(self.tab_main)
        self.checkBox_lock8.setObjectName(u"checkBox_lock8")
        self.checkBox_lock8.setGeometry(QRect(470, 420, 21, 24))
        self.label_3 = QLabel(self.tab_main)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(330, 190, 21, 20))
        self.label_26 = QLabel(self.tab_main)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(540, 380, 171, 20))
        self.label_5 = QLabel(self.tab_main)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(590, 190, 21, 20))
        self.checkBox_enable7 = QCheckBox(self.tab_main)
        self.checkBox_enable7.setObjectName(u"checkBox_enable7")
        self.checkBox_enable7.setGeometry(QRect(420, 340, 21, 24))
        self.lineEdit_b1 = QLineEdit(self.tab_main)
        self.lineEdit_b1.setObjectName(u"lineEdit_b1")
        self.lineEdit_b1.setGeometry(QRect(150, 270, 101, 21))
        self.label_13 = QLabel(self.tab_main)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(0, 310, 181, 20))
        self.checkBox_enable4 = QCheckBox(self.tab_main)
        self.checkBox_enable4.setObjectName(u"checkBox_enable4")
        self.checkBox_enable4.setGeometry(QRect(270, 340, 21, 24))
        self.label_20 = QLabel(self.tab_main)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(380, 270, 131, 20))
        self.label_22 = QLabel(self.tab_main)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(350, 270, 21, 20))
        self.checkBox_lock7 = QCheckBox(self.tab_main)
        self.checkBox_lock7.setObjectName(u"checkBox_lock7")
        self.checkBox_lock7.setGeometry(QRect(420, 420, 21, 24))
        self.checkBox_lock5 = QCheckBox(self.tab_main)
        self.checkBox_lock5.setObjectName(u"checkBox_lock5")
        self.checkBox_lock5.setGeometry(QRect(320, 420, 21, 24))
        self.checkBox_lock3 = QCheckBox(self.tab_main)
        self.checkBox_lock3.setObjectName(u"checkBox_lock3")
        self.checkBox_lock3.setGeometry(QRect(220, 420, 21, 24))
        self.label_12 = QLabel(self.tab_main)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(280, 230, 41, 20))
        self.label_23 = QLabel(self.tab_main)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(500, 360, 51, 20))
        self.lineEdit_c0 = QLineEdit(self.tab_main)
        self.lineEdit_c0.setObjectName(u"lineEdit_c0")
        self.lineEdit_c0.setGeometry(QRect(220, 190, 101, 21))
        self.checkBox_enable8 = QCheckBox(self.tab_main)
        self.checkBox_enable8.setObjectName(u"checkBox_enable8")
        self.checkBox_enable8.setGeometry(QRect(470, 340, 21, 24))
        self.lineEdit_p2 = QLineEdit(self.tab_main)
        self.lineEdit_p2.setObjectName(u"lineEdit_p2")
        self.lineEdit_p2.setGeometry(QRect(250, 250, 101, 21))
        self.checkBox_enable1 = QCheckBox(self.tab_main)
        self.checkBox_enable1.setObjectName(u"checkBox_enable1")
        self.checkBox_enable1.setGeometry(QRect(120, 340, 21, 24))
        self.lineEdit_p1 = QLineEdit(self.tab_main)
        self.lineEdit_p1.setObjectName(u"lineEdit_p1")
        self.lineEdit_p1.setGeometry(QRect(150, 250, 101, 21))
        self.checkBox_lock4 = QCheckBox(self.tab_main)
        self.checkBox_lock4.setObjectName(u"checkBox_lock4")
        self.checkBox_lock4.setGeometry(QRect(270, 420, 21, 24))
        self.checkBox_enable2 = QCheckBox(self.tab_main)
        self.checkBox_enable2.setObjectName(u"checkBox_enable2")
        self.checkBox_enable2.setGeometry(QRect(170, 340, 21, 24))
        self.checkBox_lock2 = QCheckBox(self.tab_main)
        self.checkBox_lock2.setObjectName(u"checkBox_lock2")
        self.checkBox_lock2.setGeometry(QRect(170, 420, 21, 24))
        self.label_10 = QLabel(self.tab_main)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(0, 270, 141, 20))
        self.checkBox_lock1 = QCheckBox(self.tab_main)
        self.checkBox_lock1.setObjectName(u"checkBox_lock1")
        self.checkBox_lock1.setGeometry(QRect(120, 420, 21, 24))
        self.label_18 = QLabel(self.tab_main)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(0, 420, 71, 20))
        self.label_16 = QLabel(self.tab_main)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(0, 380, 81, 20))
        self.lineEdit_c3 = QLineEdit(self.tab_main)
        self.lineEdit_c3.setObjectName(u"lineEdit_c3")
        self.lineEdit_c3.setGeometry(QRect(610, 190, 101, 21))
        self.label_17 = QLabel(self.tab_main)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(0, 400, 81, 20))
        self.label_8 = QLabel(self.tab_main)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(0, 170, 461, 20))
        font1 = QFont()
        font1.setBold(True)
        self.label_8.setFont(font1)
        self.label_15 = QLabel(self.tab_main)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(0, 340, 61, 20))
        self.radioButton_vol = QRadioButton(self.tab_main)
        self.radioButton_vol.setObjectName(u"radioButton_vol")
        self.radioButton_vol.setGeometry(QRect(450, 250, 71, 24))
        self.radioButton_vol.setChecked(False)
        self.label_2 = QLabel(self.tab_main)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(200, 190, 21, 20))
        self.checkBox_enable5 = QCheckBox(self.tab_main)
        self.checkBox_enable5.setObjectName(u"checkBox_enable5")
        self.checkBox_enable5.setGeometry(QRect(320, 340, 21, 24))
        self.line_3 = QFrame(self.tab_main)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(0, 290, 781, 20))
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_25 = QLabel(self.tab_main)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(500, 400, 21, 20))
        self.radioButton_lgm = QRadioButton(self.tab_main)
        self.radioButton_lgm.setObjectName(u"radioButton_lgm")
        self.radioButton_lgm.setGeometry(QRect(380, 250, 71, 24))
        self.radioButton_lgm.setChecked(True)
        self.checkBox_enable3 = QCheckBox(self.tab_main)
        self.checkBox_enable3.setObjectName(u"checkBox_enable3")
        self.checkBox_enable3.setGeometry(QRect(220, 340, 21, 24))
        self.label_11 = QLabel(self.tab_main)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(180, 230, 41, 20))
        self.label_9 = QLabel(self.tab_main)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(0, 250, 141, 20))
        self.lineEdit_c1 = QLineEdit(self.tab_main)
        self.lineEdit_c1.setObjectName(u"lineEdit_c1")
        self.lineEdit_c1.setGeometry(QRect(350, 190, 101, 21))
        self.lineEdit_c2 = QLineEdit(self.tab_main)
        self.lineEdit_c2.setObjectName(u"lineEdit_c2")
        self.lineEdit_c2.setGeometry(QRect(480, 190, 101, 21))
        self.checkBox_enable6 = QCheckBox(self.tab_main)
        self.checkBox_enable6.setObjectName(u"checkBox_enable6")
        self.checkBox_enable6.setGeometry(QRect(370, 340, 21, 24))
        self.label = QLabel(self.tab_main)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(0, 190, 181, 20))
        self.label_24 = QLabel(self.tab_main)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(500, 380, 21, 20))
        self.label_19 = QLabel(self.tab_main)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(540, 360, 171, 20))
        self.label_27 = QLabel(self.tab_main)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(540, 400, 171, 20))
        self.label_4 = QLabel(self.tab_main)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(460, 190, 21, 20))
        self.label_14 = QLabel(self.tab_main)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(0, 360, 91, 20))
        self.label_21 = QLabel(self.tab_main)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(350, 250, 21, 20))
        self.tableWidget = QTableWidget(self.tab_main)
        if (self.tableWidget.columnCount() < 8):
            self.tableWidget.setColumnCount(8)
        if (self.tableWidget.rowCount() < 3):
            self.tableWidget.setRowCount(3)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(100, 360, 401, 61))
        self.tableWidget.setFrameShape(QFrame.Shape.NoFrame)
        self.tableWidget.setLineWidth(1)
        self.tableWidget.setAutoScroll(False)
        self.tableWidget.setEditTriggers(QAbstractItemView.EditTrigger.AllEditTriggers)
        self.tableWidget.setProperty(u"showDropIndicator", False)
        self.tableWidget.setDragDropOverwriteMode(False)
        self.tableWidget.setSelectionMode(QAbstractItemView.SelectionMode.ExtendedSelection)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setRowCount(3)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(50)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setMinimumSectionSize(20)
        self.tableWidget.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.label_28 = QLabel(self.tab_main)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(0, 440, 71, 20))
        self.checkBox_sum_1 = QCheckBox(self.tab_main)
        self.checkBox_sum_1.setObjectName(u"checkBox_sum_1")
        self.checkBox_sum_1.setGeometry(QRect(120, 440, 21, 24))
        self.checkBox_sum_2 = QCheckBox(self.tab_main)
        self.checkBox_sum_2.setObjectName(u"checkBox_sum_2")
        self.checkBox_sum_2.setGeometry(QRect(170, 440, 21, 24))
        self.checkBox_sum_3 = QCheckBox(self.tab_main)
        self.checkBox_sum_3.setObjectName(u"checkBox_sum_3")
        self.checkBox_sum_3.setGeometry(QRect(220, 440, 21, 24))
        self.checkBox_sum_4 = QCheckBox(self.tab_main)
        self.checkBox_sum_4.setObjectName(u"checkBox_sum_4")
        self.checkBox_sum_4.setGeometry(QRect(270, 440, 21, 24))
        self.checkBox_sum_5 = QCheckBox(self.tab_main)
        self.checkBox_sum_5.setObjectName(u"checkBox_sum_5")
        self.checkBox_sum_5.setGeometry(QRect(320, 440, 21, 24))
        self.checkBox_sum_6 = QCheckBox(self.tab_main)
        self.checkBox_sum_6.setObjectName(u"checkBox_sum_6")
        self.checkBox_sum_6.setGeometry(QRect(370, 440, 21, 24))
        self.checkBox_sum_7 = QCheckBox(self.tab_main)
        self.checkBox_sum_7.setObjectName(u"checkBox_sum_7")
        self.checkBox_sum_7.setGeometry(QRect(420, 440, 21, 24))
        self.checkBox_sum_8 = QCheckBox(self.tab_main)
        self.checkBox_sum_8.setObjectName(u"checkBox_sum_8")
        self.checkBox_sum_8.setGeometry(QRect(470, 440, 21, 24))
        self.tabWidget.addTab(self.tab_main, "")
        self.tab_about = QWidget()
        self.tab_about.setObjectName(u"tab_about")
        sizePolicy.setHeightForWidth(self.tab_about.sizePolicy().hasHeightForWidth())
        self.tab_about.setSizePolicy(sizePolicy)
        self.tab_about.setSizeIncrement(QSize(1, 1))
        self.label_29 = QLabel(self.tab_about)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(10, 10, 101, 20))
        self.label_30 = QLabel(self.tab_about)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(10, 30, 101, 20))
        self.label_31 = QLabel(self.tab_about)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(10, 50, 101, 20))
        self.label_32 = QLabel(self.tab_about)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(10, 70, 191, 20))
        self.label_32.setTextFormat(Qt.TextFormat.RichText)
        self.label_32.setOpenExternalLinks(True)
        self.label_32.setTextInteractionFlags(Qt.TextInteractionFlag.LinksAccessibleByMouse|Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_33 = QLabel(self.tab_about)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 90, 261, 20))
        self.label_33.setTextFormat(Qt.TextFormat.RichText)
        self.label_33.setOpenExternalLinks(True)
        self.label_33.setTextInteractionFlags(Qt.TextInteractionFlag.LinksAccessibleByMouse|Qt.TextInteractionFlag.TextSelectableByMouse)
        self.label_34 = QLabel(self.tab_about)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(10, 110, 221, 20))
        self.label_35 = QLabel(self.tab_about)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(10, 180, 121, 20))
        self.label_36 = QLabel(self.tab_about)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(10, 200, 461, 20))
        self.label_37 = QLabel(self.tab_about)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(10, 220, 751, 20))
        self.label_38 = QLabel(self.tab_about)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(10, 240, 461, 20))
        self.label_39 = QLabel(self.tab_about)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(10, 130, 301, 20))
        self.tabWidget.addTab(self.tab_about, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"GPCurve", None))

        __sortingEnabled = self.list_data.isSortingEnabled()
        self.list_data.setSortingEnabled(False)
        ___qlistwidgetitem = self.list_data.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("MainWindow", u"drag GPC txt data file", None));
        self.list_data.setSortingEnabled(__sortingEnabled)

        self.label_7.setText(QCoreApplication.translate("MainWindow", u"*comma separator expected (as in txt file)", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Vol boundaries for txt data file:", None))

        __sortingEnabled1 = self.list_const.isSortingEnabled()
        self.list_const.setSortingEnabled(False)
        ___qlistwidgetitem1 = self.list_const.item(0)
        ___qlistwidgetitem1.setText(QCoreApplication.translate("MainWindow", u"drag constants pdf data file / folder with these files named like YYYYMMDDRI.pdf", None));
        self.list_const.setSortingEnabled(__sortingEnabled1)

        self.checkBox_vol.setText(QCoreApplication.translate("MainWindow", u"Vol plot", None))
        self.checkBox_reuse.setText(QCoreApplication.translate("MainWindow", u"Reuse last figure", None))
        self.checkBox_clean.setText(QCoreApplication.translate("MainWindow", u"Clean plot", None))
        self.pushButton_start.setText(QCoreApplication.translate("MainWindow", u"Start", None))
        self.checkBox_lock6.setText("")
        self.checkBox_lock8.setText("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"C1:", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"can be left", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"C3:", None))
        self.checkBox_enable7.setText("")
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Multi gauss interpolation:", None))
        self.checkBox_enable4.setText("")
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"use nomalized intensity", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"--->", None))
        self.checkBox_lock7.setText("")
        self.checkBox_lock5.setText("")
        self.checkBox_lock3.setText("")
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Point2", None))
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"--->", None))
        self.checkBox_enable8.setText("")
        self.checkBox_enable1.setText("")
        self.checkBox_lock4.setText("")
        self.checkBox_enable2.setText("")
        self.checkBox_lock2.setText("")
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"Manual baseline values:", None))
        self.checkBox_lock1.setText("")
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Lock center", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Center guess", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"Sigma guess", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Optional settings:", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"Enable ", None))
        self.radioButton_vol.setText(QCoreApplication.translate("MainWindow", u"Use vol", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"C0:", None))
        self.checkBox_enable5.setText("")
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"--->", None))
        self.radioButton_lgm.setText(QCoreApplication.translate("MainWindow", u"Use lgM", None))
        self.checkBox_enable3.setText("")
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Point1", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Manual peak boundaries:", None))
        self.lineEdit_c2.setText("")
        self.checkBox_enable6.setText("")
        self.label.setText(QCoreApplication.translate("MainWindow", u"Use manual calibration constants:", None))
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"--->", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"guess entries", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"empty", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"C2:", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"Amplitude guess", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"--->", None))
        self.label_28.setText(QCoreApplication.translate("MainWindow", u"Partial sum", None))
        self.checkBox_sum_1.setText("")
        self.checkBox_sum_2.setText("")
        self.checkBox_sum_3.setText("")
        self.checkBox_sum_4.setText("")
        self.checkBox_sum_5.setText("")
        self.checkBox_sum_6.setText("")
        self.checkBox_sum_7.setText("")
        self.checkBox_sum_8.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_main), QCoreApplication.translate("MainWindow", u"Main", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"Version: alpha 2.3", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"\u00a9 2025 MirChemi", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"License: MIT", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>Contact: <a href=\"mailto:mirekchemis@gmail.com\"><span style=\" text-decoration: underline; color:#004275;\">mirekchemis@gmail.com</span></a></p></body></html>", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>GitHub: <a href=\"https://github.com/MirChemi/GPCurve\"><span style=\" text-decoration: underline; color:#004275;\">https://github.com/MirChemi/GPCurve</span></a></p></body></html>", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"Modify config.ini for advanced settings", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Usage requirements:", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"1. Ensure the data files (`xxx.pdf` and `xxx.txt`) are in the same folder ", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"2. Ensure that you have a PDF file containing calibration constants or a folder with such files named in the format \"yearmonthdate[RI-or-UV]\"", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"Check the example and constants_example folders in the GitHub repository", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"All generated files are stored in the output folder", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_about), QCoreApplication.translate("MainWindow", u"Info", None))
    # retranslateUi

